name: update release
on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *
jobs:
  update-release:
    name: update release
    runs-on: ubuntu-latest
    steps:
      - name: Set safe directory # https://github.com/actions/checkout/issues/760
        run: |
          set -x
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run update script
        run: |
          python -m pip install aiohttp
          python update.py
        shell: bash

      - name: Commit and push changes
        shell: bash
        run: |
          git config --global user.name "Kien Nguyen Tuan"
          git config --global user.email "kiennt2609@gmail.com"
          bash git-partial-push.sh
