name: update release
on:
  workflow_dispatch:
  schedule:
  - cron: 30 0 * * *
jobs:
  update-release:
    name: update release
    runs-on: ubuntu-latest
    steps:
    - name: Set safe directory # https://github.com/actions/checkout/issues/760
      run: |
        set -x
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git config --global --add safe.directory /github/workspace
    
    - uses: actions/checkout@v3

    - name: Run update script
      run: |
        bash get-fonts.sh
      shell: bash

    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        push-branch: 'master'
        commit-message: 'Update new release'
        force-add: 'true'
        rebase: 'true'
        email: 'chadboyce@gmail.com'
        name: 'Chad Boyce'
